### ISSUE TITLE
09.01.01 As an owner, I don’t want to store big images online	

### ISSUE THREAD

**Issue by y-san-chez** [CMPUT301W23T26-0/ProjectOne#23]
## Story Points
2

## Risk
Low

**Comment by DanielSacro** [comment]
May be a camera or database thing

**Comment by DanielSacro** [comment]
May or may not be moved to "Todo by Final Checkpoint" because it's not relevant to functional use for demo purposes

**Comment by DanielSacro** [comment]
Will place this into "Todo by Final Checkpoint"

**Comment by DanielSacro** [comment]
Will look into using Glide
